apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: default
data:
  server.port: "8080"

  spring.application.name: "user-service"
  spring.datasource.url: "jdbc:postgresql://postgres:5432/payment_gateway"
  spring.datasource.username: "postgres"
  spring.datasource.hikari.auto-commit: "false"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
  spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: "false"

  spring.kafka.bootstrap-servers: "my-cluster-kafka.kafka.svc.cluster.local:9092"

  spring.servlet.multipart.enabled: "true"
  spring.servlet.multipart.max-file-size: "10MB"
  spring.servlet.multipart.max-request-size: "10MB"
  jwt.expiration-time: "3600000"

  stripe.api.key: "sk_test_51PYgn7RvpDLCTJ2LrFNta4dQLcPYUWLiXRE5LB81MeT3KJ1QjksQ0VzydPUtiU5vsgRGujRfUVyTsN0YHdPovpz900rVtVCzsh"
