apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ghcr.io/jay-abre/spring-boot-digital-wallet-ci-cd-user-service:latest
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: github-registry
