apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: default
type: Opaque
data:
  spring.datasource.password: cG9zdGdyZXM= # Base64 encoded 'postgres'
  jwt.secret: c2VjcmV0a2V5MTIzNDU2Nzg=
  super-admin.username: c3VwZXJfYWRtaW4= # Base64 encoded 'super_admin'
  super-admin.email: c3VwYXJhbWRpbkBlbWFpbC5jb20= # Base64 encoded 'superadmin@email.com'
  super-admin.first-name: Sm9obiA= # Base64 encoded 'John'
  super-admin.middle-name: SGVucnkg # Base64 encoded 'Henry'
  super-admin.last-name: RWRh # Base64 encoded 'Doe'
  super-admin.mobile-number: KzYzOTEyMzQ1Njc4OQ== # Base64 encoded '+639123456789'
  super-admin.password: UGFzc3dvcmQxMjMh # Base64 encoded 'Password123!'
  stripe.api.key: c2tfdGVzdF81MVBZZ243UnZwRExDVEoyTHJGTnRhNGRRTGNQWVVXTGlYUkU1TEI4MU1lVDNLSjFRamtzUTBWenlkUFV0aVU1dnNnUkd1alJmVVZ5VHNOMFlIZFBvdnB6OTAwclZ0VkN6c2g= # Base64 encoded Stripe API key
