apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: ClusterIP  # or LoadBalancer, or NodePort depending on your needs
  ports:
    - port: 80  # The port the service is exposed on
      targetPort: 8081  # The port your application is running on in the container
  selector:
    app: user-service
