apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: default
data:
  spring.datasource.url: "jdbc:postgresql://localhost:5432/payment_gateway"
  spring.datasource.username: "postgres"
