apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: postgres
type: Opaque
data:
  postgres.user: "cG9zdGdyZXM="  # Base64 encoded value for 'postgres'
  postgres.password: "cGFzc3dvcmQ="  # Base64 encoded value for 'password'
