apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-my-cluster-zookeeper-0
  namespace: kafka
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-nfs-storage
  hostPath:
    path: /mnt/data/zookeeper-0

