apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway-service  # This should match the matrix service name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-gateway-service
  template:
    metadata:
      labels:
        app: payment-gateway-service
    spec:
      containers:
        - name: payment-gateway-service  # This should also match the matrix service name
          image: ghcr.io/yourusername/your-repo-payment-gateway-service:latest  # This will be updated by kubectl set image
          ports:
            - containerPort: 8083
      imagePullSecrets:
        - name: github-registry