apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-gateway-config
data:
  server.port: "8083"
  spring.application.name: "payment-gateway-service"
  spring.datasource.url: "jdbc:postgresql://postgres:5432/payment_gateway"
  spring.datasource.username: "postgres"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
  spring.kafka.bootstrap-servers: "kafka:9092"
  spring.kafka.consumer.group-id: "payment-gateway-service"
  stripe.api.key: "sk_test_51PYgn7RvpDLCTJ2LrFNta4dQLcPYUWLiXRE5LB81MeT3KJ1QjksQ0VzydPUtiU5vsgRGujRfUVyTsN0YHdPovpz900rVtVCzsh"
