apiVersion: v1
kind: Secret
metadata:
  name: payment-gateway-service-secrets
  namespace: default
type: Opaque
data:
  spring.datasource.password: "cG9zdGdyZXM="  # base64 encoded value for "postgres"
  jwt.secret: "M2NmYTc2ZWYxNDkzN2MxYzBlNTIxOWY4ZmMwNTdhODBmY2QwNGE3NDIwZjhlOGJjMDo3YjE1ZGVhN2M5NzI4ZTEwNzA3YjEwZQ=="
  stripe.api.key: "c2tfdGVzdF81MVBZbjdSdnhMQ2hYT1BvTkZGQmJ3eW5jYzJDOVVOMlFzZW4tMzA0TGxKM2JQS0w0a2FvVDN2S0NBVD0="  # base64 encoded value
