apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-service
  labels:
    app: payment-gateway-service
spec:
  type: NodePort  # Change to NodePort
  ports:
    - port: 80          # The port the service is exposed on
      targetPort: 8082  # The port your application is running on in the container
      nodePort: 30002   # The external port on the nodes (choose a port in the range 30000-32767)
  selector:
    app: payment-gateway-service
