apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: ghcr.io/jay-abre/spring-boot-digital-wallet-ci-cd-account-service:latest
          ports:
            - containerPort: 8085
          env:
            # Environment variables sourced from ConfigMap
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: spring.application.name
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: spring.datasource.username
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: spring.kafka.bootstrap-servers
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: spring.kafka.consumer.group-id
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: spring.jpa.hibernate.ddl-auto
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: spring.jpa.properties.hibernate.dialect
            - name: LOGGING_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: account-service-config
                  key: logging.level.com.electric_titans.accountservice

            # Environment variables sourced from Secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: spring.datasource.password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: jwt.secret
      imagePullSecrets:
        - name: github-registry
