apiVersion: v1
kind: Secret
metadata:
  name: account-service-secrets
type: Opaque
data:
  spring.datasource.password: cG9zdGdyZXM= # Base64 encoded value of 'postgres'
  jwt.secret: M2NmYTc2ZWYxNDkzN2MxYzBlYTUxOWY4ZmMwNTdhODBmY2QwNGE3NDIwZjhlOGJjZDBhNzU2N2MyNzJlMDA3Yg==
