apiVersion: v1
kind: Secret
metadata:
  name: account-service-secrets
type: Opaque
data:
  spring.datasource.password: cG9zdGdyZXM= # Base64 encoded value of 'postgres'
  jwt.secret: M2NmYTc2ZWYxNDkzN2MxYzBlYTE1OTY4Zjk0ZTA0YTc0MGY4ZTg2YmNkMGE3NTZkMDA3Yg== # Base64 encoded value of '3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b'
