apiVersion: v1
kind: Service
metadata:
  name: account-service  # Replace with your service name
  labels:
    app: account-service  # Replace with your service name
spec:
  type: ClusterIP  # or LoadBalancer, or NodePort depending on your needs
  ports:
    - port: 80  # The port the service is exposed on
      targetPort: 8082  # The port your application is running on in the container
  selector:
    app: account-service  # This should match the labels in your deployment