name: Microservices CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [account-service, user-service, payment-gateway-service]
    steps:
      - uses: actions/checkout@v2

      - name: List files
        run: ls -R

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build parent POM
        run: mvn clean install -f ./payment-gateway-services/pom.xml

      - name: Build and package service
        run: mvn clean package -f ./payment-gateway-services/${{ matrix.service }}/pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./payment-gateway-services/${{ matrix.service }}
          file: ./payment-gateway-services/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}-${{ matrix.service }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Change to service directory
        run: cd payment-gateway-services/${{ matrix.service }}/kubernetes

      - name: Deploy to local Kubernetes
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          kubectl set image deployment/${{ matrix.service }} ${{ matrix.service }}=${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}-${{ matrix.service }}:${{ github.sha }}
