name: Microservices CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [user-service, account-service, payment-gateway-service]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build parent POM
        run: mvn clean install -f ./payment-gateway-services/pom.xml

      - name: Build and package service
        run: mvn clean package -f ./payment-gateway-services/${{ matrix.service }}/pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./payment-gateway-services/${{ matrix.service }}
          file: ./payment-gateway-services/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}-${{ matrix.service }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: self-hosted
    needs: build
    strategy:
      matrix:
        service: [user-service, account-service, payment-gateway-service]
    steps:
      - name: Deploy PostgreSQL to Kubernetes
        run: |
          echo "Deploying PostgreSQL to Kubernetes"
          kubectl apply -f payment-gateway-services/common-kubernetes/postgres-pv.yml
          kubectl apply -f payment-gateway-services/common-kubernetes/postgres-pvc.yml
          kubectl apply -f payment-gateway-services/common-kubernetes/postgres-secrets.yml
          kubectl apply -f payment-gateway-services/common-kubernetes/postgres-deployment.yml
          kubectl apply -f payment-gateway-services/common-kubernetes/postgres-service.yml

      - name: Apply secrets for the microservice
        run: |
          echo "Applying secrets for ${{ matrix.service }}"
          kubectl apply -f payment-gateway-services/${{ matrix.service }}/kubernetes/secret.yml


      - name: Deploy microservices to Kubernetes
        run: |
          echo "Deploying ${{ matrix.service }} to Kubernetes"
          kubectl apply -f payment-gateway-services/${{ matrix.service }}/kubernetes/deployment.yml
          kubectl apply -f payment-gateway-services/${{ matrix.service }}/kubernetes/service.yml
          kubectl set image deployment/${{ matrix.service }} ${{ matrix.service }}=${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}-${{ matrix.service }}:${{ github.sha }}

      - name: Verify Kubernetes deployments
        run: |
          kubectl get deployments
          kubectl get services

      - name: Print Environment Variables
        run: |
          echo "Matrix Service: ${{ matrix.service }}"
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Base Image Name: ${{ env.BASE_IMAGE_NAME }}"
          echo "GitHub SHA: ${{ github.sha }}"

      - name: Echo Kubectl Command
        run: |
          echo "kubectl set image deployment/${{ matrix.service }} ${matrix.service}=${{ env.REGISTRY }}/${{ env.BASE_IMAGE_NAME }}-${{ matrix.service }}:${{ github.sha }}"
